# Generated by Django 3.1.6 on 2021-04-04 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210404_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 11, 32, 4, 849014)),
        ),
    ]
