# Generated by Django 3.1.6 on 2021-03-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210310_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='final_bid',
            field=models.IntegerField(default=0),
        ),
    ]
