# Generated by Django 3.1.6 on 2021-03-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_final_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='start_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='start_bid',
            field=models.ManyToManyField(default=0, to='auctions.Listing'),
        ),
    ]
