# Generated by Django 3.1.6 on 2021-03-15 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_user_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='final_bid',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
