# Generated by Django 3.1.6 on 2021-03-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210315_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='final_bid',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
