# Generated by Django 3.1.6 on 2021-03-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210315_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='start_bid',
        ),
    ]
