# Generated by Django 3.1.6 on 2021-03-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_bid_final_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100000),
        ),
    ]
