# Generated by Django 3.1.6 on 2021-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210315_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
    ]
