# Generated by Django 3.1.6 on 2021-03-21 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210318_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watching',
        ),
        migrations.AddField(
            model_name='listing',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watchedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
