# Generated by Django 3.1.6 on 2021-03-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210322_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.ForeignKey(default=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='biddeditems', to=settings.AUTH_USER_MODEL), null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='wonitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
