# Generated by Django 3.1.6 on 2021-03-22 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210322_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winner',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='wonitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
