# Generated by Django 3.1.6 on 2021-03-26 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20210325_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 17, 44, 41, 96721)),
        ),
    ]
